name: corpse_tools
description: Extract and replace text in a readable way for Corpse Party games.
version: 0.1.5
homepage: https://github.com/KyouinDev/corpse-tools
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.1
