name: corpse_tools
description: A tool to extract/replace text in a readable way for Corpse Party .BIN files.
version: 0.1.0
homepage: https://github.com/KyouinDev/corpse_tools

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
