name: corpse_tools
description: A tool to extract/replace text in a readable way for Corpse Party .BIN files.
version: 0.1.2
homepage: https://github.com/KyouinDev/corpse_tools
publish_to: none

environment:
  sdk: '>=2.12.2 <3.0.0'

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.8
