name: corpse_tools
description: A tool to extract/replace text in a readable way for Corpse Party .BIN files.
version: 0.1.4
homepage: https://github.com/KyouinDev/corpse_tools
publish_to: none

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.1
